version: '2'
services:
  nginx_webdav:
#    image: maltokyo/docker-nginx-webdav # comment out this line if you are building from source.
    build: . # comment out this line if you are just pulling the docker hub image.
#    ports: # enable this if you are not using reverse proxy, otherwise leave commented out
#      - "80:80"
    volumes:
      - "/path/to/your/share:/media/data"
    environment:
      USERNAME: your_webdav_user
      PASSWORD: your_webdav_passwd

---
services:
  nginx_webdav:
    image: ghcr.io/the0mikkel/docker-nginx-webdav:latest
    volumes:
      - "./data:/media/data"
    environment:
      USERNAME: demo-user
      PASSWORD: seom-ldonge-egepwtngd-wept3ignwerpig

      # PROXY
      VIRTUAL_HOST: webdav.hel1.hetzner.themikkel.dk
      LETSENCRYPT_HOST: webdav.hel1.hetzner.themikkel.dk
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
